Description: "
  file processing scheduler for aws ecs.
"

#Parameters

Resources:
  jobQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      # delete jobs not processed within 8 hours
      MessageRetentionPeriod: 19200
      # allow job loading 20 seconds before container shutdown
      ReceiveMessageWaitTimeSeconds: 20
      # allow 10 mins before job marked for reprocessing
      VisibilityTimeout: 600
  jobScheduler:
    Type: "AWS::Lambda::Function"
    Properties:
      # code built/packaged via gradle script
      Code:
        # TODO: make code bucket a param
        S3Bucket: "bns.ds.code"
        # TODO: make key a param
        S3Key: "lambda-0.0.1-all.jar"
      Description: "
        loads jobs uploaded to the job bucket into the job queue 
        and starts necessary processing containers according to queueSize.
      "
      Handler: "io.rbi.aws.lambda.scheduling.S3FileScheduler"
      # TODO: make role name a param
      Role: "arn:aws:iam::448132366281:role/lambda-exec"
      Runtime: java8
      Timeout: 60
  # not there just yet
  #cluster:
  # Type: "AWS::ECS::Cluster"